// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: egress_policy.proto

package egresspolicypb

import (
	ateapipb "github.com/agent-substrate/substrate/pkg/proto/ateapipb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEffectiveEgressPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *ateapipb.ObjectRef    `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	ActorUid      string                 `protobuf:"bytes,2,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEffectiveEgressPolicyRequest) Reset() {
	*x = GetEffectiveEgressPolicyRequest{}
	mi := &file_egress_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectiveEgressPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectiveEgressPolicyRequest) ProtoMessage() {}

func (x *GetEffectiveEgressPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egress_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectiveEgressPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetEffectiveEgressPolicyRequest) Descriptor() ([]byte, []int) {
	return file_egress_policy_proto_rawDescGZIP(), []int{0}
}

func (x *GetEffectiveEgressPolicyRequest) GetActor() *ateapipb.ObjectRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *GetEffectiveEgressPolicyRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

type EffectiveEgressPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *ateapipb.EgressPolicy `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Credentials   []*ResolvedCredential  `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectiveEgressPolicy) Reset() {
	*x = EffectiveEgressPolicy{}
	mi := &file_egress_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveEgressPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveEgressPolicy) ProtoMessage() {}

func (x *EffectiveEgressPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_egress_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveEgressPolicy.ProtoReflect.Descriptor instead.
func (*EffectiveEgressPolicy) Descriptor() ([]byte, []int) {
	return file_egress_policy_proto_rawDescGZIP(), []int{1}
}

func (x *EffectiveEgressPolicy) GetPolicy() *ateapipb.EgressPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *EffectiveEgressPolicy) GetCredentials() []*ResolvedCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type ResolvedCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedCredential) Reset() {
	*x = ResolvedCredential{}
	mi := &file_egress_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedCredential) ProtoMessage() {}

func (x *ResolvedCredential) ProtoReflect() protoreflect.Message {
	mi := &file_egress_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedCredential.ProtoReflect.Descriptor instead.
func (*ResolvedCredential) Descriptor() ([]byte, []int) {
	return file_egress_policy_proto_rawDescGZIP(), []int{2}
}

func (x *ResolvedCredential) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolvedCredential) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_egress_policy_proto protoreflect.FileDescriptor

const file_egress_policy_proto_rawDesc = "" +
	"\n" +
	"\x13egress_policy.proto\x12\fegresspolicy\x1a\x1fpkg/proto/ateapipb/ateapi.proto\"g\n" +
	"\x1fGetEffectiveEgressPolicyRequest\x12'\n" +
	"\x05actor\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\x05actor\x12\x1b\n" +
	"\tactor_uid\x18\x02 \x01(\tR\bactorUid\"\x89\x01\n" +
	"\x15EffectiveEgressPolicy\x12,\n" +
	"\x06policy\x18\x01 \x01(\v2\x14.ateapi.EgressPolicyR\x06policy\x12B\n" +
	"\vcredentials\x18\x02 \x03(\v2 .egresspolicy.ResolvedCredentialR\vcredentials\">\n" +
	"\x12ResolvedCredential\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value2|\n" +
	"\bResolver\x12p\n" +
	"\x18GetEffectiveEgressPolicy\x12-.egresspolicy.GetEffectiveEgressPolicyRequest\x1a#.egresspolicy.EffectiveEgressPolicy\"\x00BDZBgithub.com/agent-substrate/substrate/internal/proto/egresspolicypbb\x06proto3"

var (
	file_egress_policy_proto_rawDescOnce sync.Once
	file_egress_policy_proto_rawDescData []byte
)

func file_egress_policy_proto_rawDescGZIP() []byte {
	file_egress_policy_proto_rawDescOnce.Do(func() {
		file_egress_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_egress_policy_proto_rawDesc), len(file_egress_policy_proto_rawDesc)))
	})
	return file_egress_policy_proto_rawDescData
}

var file_egress_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_egress_policy_proto_goTypes = []any{
	(*GetEffectiveEgressPolicyRequest)(nil), // 0: egresspolicy.GetEffectiveEgressPolicyRequest
	(*EffectiveEgressPolicy)(nil),           // 1: egresspolicy.EffectiveEgressPolicy
	(*ResolvedCredential)(nil),              // 2: egresspolicy.ResolvedCredential
	(*ateapipb.ObjectRef)(nil),              // 3: ateapi.ObjectRef
	(*ateapipb.EgressPolicy)(nil),           // 4: ateapi.EgressPolicy
}
var file_egress_policy_proto_depIdxs = []int32{
	3, // 0: egresspolicy.GetEffectiveEgressPolicyRequest.actor:type_name -> ateapi.ObjectRef
	4, // 1: egresspolicy.EffectiveEgressPolicy.policy:type_name -> ateapi.EgressPolicy
	2, // 2: egresspolicy.EffectiveEgressPolicy.credentials:type_name -> egresspolicy.ResolvedCredential
	0, // 3: egresspolicy.Resolver.GetEffectiveEgressPolicy:input_type -> egresspolicy.GetEffectiveEgressPolicyRequest
	1, // 4: egresspolicy.Resolver.GetEffectiveEgressPolicy:output_type -> egresspolicy.EffectiveEgressPolicy
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_egress_policy_proto_init() }
func file_egress_policy_proto_init() {
	if File_egress_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_egress_policy_proto_rawDesc), len(file_egress_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_egress_policy_proto_goTypes,
		DependencyIndexes: file_egress_policy_proto_depIdxs,
		MessageInfos:      file_egress_policy_proto_msgTypes,
	}.Build()
	File_egress_policy_proto = out.File
	file_egress_policy_proto_goTypes = nil
	file_egress_policy_proto_depIdxs = nil
}
