// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: internal/proto/egresspb/egress.proto

package egresspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EgressPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultAction string                 `protobuf:"bytes,1,opt,name=default_action,json=defaultAction,proto3" json:"default_action,omitempty"`
	Allow         []*EgressPolicyRule    `protobuf:"bytes,2,rep,name=allow,proto3" json:"allow,omitempty"`
	Deny          []*EgressPolicyRule    `protobuf:"bytes,3,rep,name=deny,proto3" json:"deny,omitempty"`
	Audit         *EgressAuditPolicy     `protobuf:"bytes,4,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressPolicy) Reset() {
	*x = EgressPolicy{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPolicy) ProtoMessage() {}

func (x *EgressPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPolicy.ProtoReflect.Descriptor instead.
func (*EgressPolicy) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{0}
}

func (x *EgressPolicy) GetDefaultAction() string {
	if x != nil {
		return x.DefaultAction
	}
	return ""
}

func (x *EgressPolicy) GetAllow() []*EgressPolicyRule {
	if x != nil {
		return x.Allow
	}
	return nil
}

func (x *EgressPolicy) GetDeny() []*EgressPolicyRule {
	if x != nil {
		return x.Deny
	}
	return nil
}

func (x *EgressPolicy) GetAudit() *EgressAuditPolicy {
	if x != nil {
		return x.Audit
	}
	return nil
}

type EgressPolicyRule struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	To            []*EgressPolicyDestination `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Ports         []*EgressPort              `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	Tls           *EgressTLSPolicy           `protobuf:"bytes,3,opt,name=tls,proto3" json:"tls,omitempty"`
	Credentials   *EgressCredentialPolicy    `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressPolicyRule) Reset() {
	*x = EgressPolicyRule{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPolicyRule) ProtoMessage() {}

func (x *EgressPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPolicyRule.ProtoReflect.Descriptor instead.
func (*EgressPolicyRule) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{1}
}

func (x *EgressPolicyRule) GetTo() []*EgressPolicyDestination {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EgressPolicyRule) GetPorts() []*EgressPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *EgressPolicyRule) GetTls() *EgressTLSPolicy {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *EgressPolicyRule) GetCredentials() *EgressCredentialPolicy {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type EgressPolicyDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Cidr          string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressPolicyDestination) Reset() {
	*x = EgressPolicyDestination{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPolicyDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPolicyDestination) ProtoMessage() {}

func (x *EgressPolicyDestination) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPolicyDestination.ProtoReflect.Descriptor instead.
func (*EgressPolicyDestination) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{2}
}

func (x *EgressPolicyDestination) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EgressPolicyDestination) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type EgressPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressPort) Reset() {
	*x = EgressPort{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPort) ProtoMessage() {}

func (x *EgressPort) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPort.ProtoReflect.Descriptor instead.
func (*EgressPort) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{3}
}

func (x *EgressPort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EgressPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type EgressTLSPolicy struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Mode          string                    `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Required      bool                      `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Intercept     *EgressTLSInterceptPolicy `protobuf:"bytes,3,opt,name=intercept,proto3" json:"intercept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressTLSPolicy) Reset() {
	*x = EgressTLSPolicy{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressTLSPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressTLSPolicy) ProtoMessage() {}

func (x *EgressTLSPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressTLSPolicy.ProtoReflect.Descriptor instead.
func (*EgressTLSPolicy) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{4}
}

func (x *EgressTLSPolicy) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *EgressTLSPolicy) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *EgressTLSPolicy) GetIntercept() *EgressTLSInterceptPolicy {
	if x != nil {
		return x.Intercept
	}
	return nil
}

type EgressTLSInterceptPolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IssuerSecretRef  *SecretReference       `protobuf:"bytes,1,opt,name=issuer_secret_ref,json=issuerSecretRef,proto3" json:"issuer_secret_ref,omitempty"`
	ValidateUpstream bool                   `protobuf:"varint,2,opt,name=validate_upstream,json=validateUpstream,proto3" json:"validate_upstream,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EgressTLSInterceptPolicy) Reset() {
	*x = EgressTLSInterceptPolicy{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressTLSInterceptPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressTLSInterceptPolicy) ProtoMessage() {}

func (x *EgressTLSInterceptPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressTLSInterceptPolicy.ProtoReflect.Descriptor instead.
func (*EgressTLSInterceptPolicy) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{5}
}

func (x *EgressTLSInterceptPolicy) GetIssuerSecretRef() *SecretReference {
	if x != nil {
		return x.IssuerSecretRef
	}
	return nil
}

func (x *EgressTLSInterceptPolicy) GetValidateUpstream() bool {
	if x != nil {
		return x.ValidateUpstream
	}
	return false
}

type EgressCredentialPolicy struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Inject        []*EgressCredentialInjection `protobuf:"bytes,1,rep,name=inject,proto3" json:"inject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressCredentialPolicy) Reset() {
	*x = EgressCredentialPolicy{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressCredentialPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressCredentialPolicy) ProtoMessage() {}

func (x *EgressCredentialPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressCredentialPolicy.ProtoReflect.Descriptor instead.
func (*EgressCredentialPolicy) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{6}
}

func (x *EgressCredentialPolicy) GetInject() []*EgressCredentialInjection {
	if x != nil {
		return x.Inject
	}
	return nil
}

type EgressCredentialInjection struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Header        string                     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ValueFrom     *EgressCredentialValueFrom `protobuf:"bytes,2,opt,name=value_from,json=valueFrom,proto3" json:"value_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressCredentialInjection) Reset() {
	*x = EgressCredentialInjection{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressCredentialInjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressCredentialInjection) ProtoMessage() {}

func (x *EgressCredentialInjection) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressCredentialInjection.ProtoReflect.Descriptor instead.
func (*EgressCredentialInjection) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{7}
}

func (x *EgressCredentialInjection) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *EgressCredentialInjection) GetValueFrom() *EgressCredentialValueFrom {
	if x != nil {
		return x.ValueFrom
	}
	return nil
}

type EgressCredentialValueFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretKeyRef  *SecretKeySelector     `protobuf:"bytes,1,opt,name=secret_key_ref,json=secretKeyRef,proto3" json:"secret_key_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressCredentialValueFrom) Reset() {
	*x = EgressCredentialValueFrom{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressCredentialValueFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressCredentialValueFrom) ProtoMessage() {}

func (x *EgressCredentialValueFrom) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressCredentialValueFrom.ProtoReflect.Descriptor instead.
func (*EgressCredentialValueFrom) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{8}
}

func (x *EgressCredentialValueFrom) GetSecretKeyRef() *SecretKeySelector {
	if x != nil {
		return x.SecretKeyRef
	}
	return nil
}

type EgressAuditPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          bool                   `protobuf:"varint,1,opt,name=logs,proto3" json:"logs,omitempty"`
	Traces        bool                   `protobuf:"varint,2,opt,name=traces,proto3" json:"traces,omitempty"`
	RedactHeaders []string               `protobuf:"bytes,3,rep,name=redact_headers,json=redactHeaders,proto3" json:"redact_headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressAuditPolicy) Reset() {
	*x = EgressAuditPolicy{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressAuditPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressAuditPolicy) ProtoMessage() {}

func (x *EgressAuditPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressAuditPolicy.ProtoReflect.Descriptor instead.
func (*EgressAuditPolicy) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{9}
}

func (x *EgressAuditPolicy) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *EgressAuditPolicy) GetTraces() bool {
	if x != nil {
		return x.Traces
	}
	return false
}

func (x *EgressAuditPolicy) GetRedactHeaders() []string {
	if x != nil {
		return x.RedactHeaders
	}
	return nil
}

type SecretReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretReference) Reset() {
	*x = SecretReference{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretReference) ProtoMessage() {}

func (x *SecretReference) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretReference.ProtoReflect.Descriptor instead.
func (*SecretReference) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{10}
}

func (x *SecretReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type SecretKeySelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretKeySelector) Reset() {
	*x = SecretKeySelector{}
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretKeySelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretKeySelector) ProtoMessage() {}

func (x *SecretKeySelector) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_egresspb_egress_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretKeySelector.ProtoReflect.Descriptor instead.
func (*SecretKeySelector) Descriptor() ([]byte, []int) {
	return file_internal_proto_egresspb_egress_proto_rawDescGZIP(), []int{11}
}

func (x *SecretKeySelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretKeySelector) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_internal_proto_egresspb_egress_proto protoreflect.FileDescriptor

const file_internal_proto_egresspb_egress_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/egresspb/egress.proto\x12\x06egress\"\xc4\x01\n" +
	"\fEgressPolicy\x12%\n" +
	"\x0edefault_action\x18\x01 \x01(\tR\rdefaultAction\x12.\n" +
	"\x05allow\x18\x02 \x03(\v2\x18.egress.EgressPolicyRuleR\x05allow\x12,\n" +
	"\x04deny\x18\x03 \x03(\v2\x18.egress.EgressPolicyRuleR\x04deny\x12/\n" +
	"\x05audit\x18\x04 \x01(\v2\x19.egress.EgressAuditPolicyR\x05audit\"\xda\x01\n" +
	"\x10EgressPolicyRule\x12/\n" +
	"\x02to\x18\x01 \x03(\v2\x1f.egress.EgressPolicyDestinationR\x02to\x12(\n" +
	"\x05ports\x18\x02 \x03(\v2\x12.egress.EgressPortR\x05ports\x12)\n" +
	"\x03tls\x18\x03 \x01(\v2\x17.egress.EgressTLSPolicyR\x03tls\x12@\n" +
	"\vcredentials\x18\x04 \x01(\v2\x1e.egress.EgressCredentialPolicyR\vcredentials\"A\n" +
	"\x17EgressPolicyDestination\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\"<\n" +
	"\n" +
	"EgressPort\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\"\x81\x01\n" +
	"\x0fEgressTLSPolicy\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12>\n" +
	"\tintercept\x18\x03 \x01(\v2 .egress.EgressTLSInterceptPolicyR\tintercept\"\x8c\x01\n" +
	"\x18EgressTLSInterceptPolicy\x12C\n" +
	"\x11issuer_secret_ref\x18\x01 \x01(\v2\x17.egress.SecretReferenceR\x0fissuerSecretRef\x12+\n" +
	"\x11validate_upstream\x18\x02 \x01(\bR\x10validateUpstream\"S\n" +
	"\x16EgressCredentialPolicy\x129\n" +
	"\x06inject\x18\x01 \x03(\v2!.egress.EgressCredentialInjectionR\x06inject\"u\n" +
	"\x19EgressCredentialInjection\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12@\n" +
	"\n" +
	"value_from\x18\x02 \x01(\v2!.egress.EgressCredentialValueFromR\tvalueFrom\"\\\n" +
	"\x19EgressCredentialValueFrom\x12?\n" +
	"\x0esecret_key_ref\x18\x01 \x01(\v2\x19.egress.SecretKeySelectorR\fsecretKeyRef\"f\n" +
	"\x11EgressAuditPolicy\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\bR\x04logs\x12\x16\n" +
	"\x06traces\x18\x02 \x01(\bR\x06traces\x12%\n" +
	"\x0eredact_headers\x18\x03 \x03(\tR\rredactHeaders\"C\n" +
	"\x0fSecretReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"9\n" +
	"\x11SecretKeySelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03keyB>Z<github.com/agent-substrate/substrate/internal/proto/egresspbb\x06proto3"

var (
	file_internal_proto_egresspb_egress_proto_rawDescOnce sync.Once
	file_internal_proto_egresspb_egress_proto_rawDescData []byte
)

func file_internal_proto_egresspb_egress_proto_rawDescGZIP() []byte {
	file_internal_proto_egresspb_egress_proto_rawDescOnce.Do(func() {
		file_internal_proto_egresspb_egress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_egresspb_egress_proto_rawDesc), len(file_internal_proto_egresspb_egress_proto_rawDesc)))
	})
	return file_internal_proto_egresspb_egress_proto_rawDescData
}

var file_internal_proto_egresspb_egress_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_proto_egresspb_egress_proto_goTypes = []any{
	(*EgressPolicy)(nil),              // 0: egress.EgressPolicy
	(*EgressPolicyRule)(nil),          // 1: egress.EgressPolicyRule
	(*EgressPolicyDestination)(nil),   // 2: egress.EgressPolicyDestination
	(*EgressPort)(nil),                // 3: egress.EgressPort
	(*EgressTLSPolicy)(nil),           // 4: egress.EgressTLSPolicy
	(*EgressTLSInterceptPolicy)(nil),  // 5: egress.EgressTLSInterceptPolicy
	(*EgressCredentialPolicy)(nil),    // 6: egress.EgressCredentialPolicy
	(*EgressCredentialInjection)(nil), // 7: egress.EgressCredentialInjection
	(*EgressCredentialValueFrom)(nil), // 8: egress.EgressCredentialValueFrom
	(*EgressAuditPolicy)(nil),         // 9: egress.EgressAuditPolicy
	(*SecretReference)(nil),           // 10: egress.SecretReference
	(*SecretKeySelector)(nil),         // 11: egress.SecretKeySelector
}
var file_internal_proto_egresspb_egress_proto_depIdxs = []int32{
	1,  // 0: egress.EgressPolicy.allow:type_name -> egress.EgressPolicyRule
	1,  // 1: egress.EgressPolicy.deny:type_name -> egress.EgressPolicyRule
	9,  // 2: egress.EgressPolicy.audit:type_name -> egress.EgressAuditPolicy
	2,  // 3: egress.EgressPolicyRule.to:type_name -> egress.EgressPolicyDestination
	3,  // 4: egress.EgressPolicyRule.ports:type_name -> egress.EgressPort
	4,  // 5: egress.EgressPolicyRule.tls:type_name -> egress.EgressTLSPolicy
	6,  // 6: egress.EgressPolicyRule.credentials:type_name -> egress.EgressCredentialPolicy
	5,  // 7: egress.EgressTLSPolicy.intercept:type_name -> egress.EgressTLSInterceptPolicy
	10, // 8: egress.EgressTLSInterceptPolicy.issuer_secret_ref:type_name -> egress.SecretReference
	7,  // 9: egress.EgressCredentialPolicy.inject:type_name -> egress.EgressCredentialInjection
	8,  // 10: egress.EgressCredentialInjection.value_from:type_name -> egress.EgressCredentialValueFrom
	11, // 11: egress.EgressCredentialValueFrom.secret_key_ref:type_name -> egress.SecretKeySelector
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_proto_egresspb_egress_proto_init() }
func file_internal_proto_egresspb_egress_proto_init() {
	if File_internal_proto_egresspb_egress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_egresspb_egress_proto_rawDesc), len(file_internal_proto_egresspb_egress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_egresspb_egress_proto_goTypes,
		DependencyIndexes: file_internal_proto_egresspb_egress_proto_depIdxs,
		MessageInfos:      file_internal_proto_egresspb_egress_proto_msgTypes,
	}.Build()
	File_internal_proto_egresspb_egress_proto = out.File
	file_internal_proto_egresspb_egress_proto_goTypes = nil
	file_internal_proto_egresspb_egress_proto_depIdxs = nil
}
